# ================================
# config/model_config.yaml
# ================================
model:
  name: "gemini-1.5-flash"
  temperature: 0.7
  max_tokens: 1024
  timeout: 30

app:
  title: "Gemini Vision Assistant"
  description: "AI-powered image analysis using Google's Gemini model"
  page_icon: "🤖"
  layout: "wide"
  
ui:
  max_file_size: 10  # MB
  allowed_extensions: ["jpg", "jpeg", "png", "webp"]
  default_prompt: "Analyze this image and provide detailed insights"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"